services:
  # Web Service
  - type: web
    name: tes-forms
    env: node
    region: oregon # Change to your preferred region
    plan: free
    buildCommand: npm install && PUPPETEER_CACHE_DIR=/opt/render/project/.cache/puppeteer npx puppeteer browsers install chrome && npm run build && node scripts/init-database.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tes-forms-db
          property: connectionString
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/.cache/puppeteer


databases:
  # PostgreSQL Database
  - name: tes-forms-db
    databaseName: tes_forms
    plan: free
    region: oregon # Same region as web service for low latency
