services:
  # Web Service
  - type: web
    name: tes-forms
    env: node
    region: oregon # Change to your preferred region
    plan: free
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tes-forms-db
          property: connectionString
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: ""

databases:
  # PostgreSQL Database
  - name: tes-forms-db
    databaseName: tes_forms
    plan: free
    region: oregon # Same region as web service for low latency
